<?xml version="1.0"?>
<robot name="yes" xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="blue">
     <color rgba="0 0 0.8 1"/>
  </material>

  <material name="cyan">
     <color rgba="0 1 1 1"/>
  </material>
<!-- -->
<!-- Base dimensions -->
<xacro:property name="basex" value="0.2" />
<xacro:property name="basey" value="0.2" />
<xacro:property name="basez" value="0.05" />

<!-- Turntable dimensions -->
<xacro:property name="turntable_height" value="0.01" />
<xacro:property name="turntable_radius" value="0.09" />

<!-- Motor dimensions -->
<xacro:property name="motorx" value="0.0356" />
<xacro:property name="motory" value="0.0355" />
<xacro:property name="motorz" value="0.0506" />

<!-- Mounting plate dimensions -->
<xacro:property name="mpx" value="0.0356" />
<xacro:property name="mpy" value="0.0355" />
<xacro:property name="mpz" value="0.0206" />

<xacro:property name="girder_len" value="0.0635" />

<!-- Base -->
<link name="base_link">
  <visual>
    <geometry>
      <box size ="${basex} ${basey} ${basez}"/>
    </geometry>
  </visual>
</link>

<link name="turntable">
  <visual>
    <geometry>
      <cylinder radius = "${turntable_radius}" length = "${turntable_height}"/>
    </geometry>
    <origin xyz ="0 0 0"/>
    <material name="blue"/>
  </visual>
</link>

<joint name="base_to_turntable" type="continuous">
  <parent link="base_link"/>
  <child link="turntable"/>
  <origin xyz="0 0 ${(basez+turntable_height)/2}"/>
  <axis xyz ="0 0 1"/>
</joint>


<xacro:macro name="motor" params="prefix z_coord parent">
<link name="${prefix}_motor">
  <visual>
    <geometry>
      <box size ="${motorx} ${motory} ${motorz}"/>
    </geometry>
    <origin xyz ="0 0 ${motorz/2}"/>
    <material name="blue"/>
  </visual>
</link>

<joint name="${parent}_to_${prefix}_motor" type="fixed">
  <parent link="${parent}"/>
  <child link="${prefix}_motor"/>
  <origin xyz="0 0 ${z_coord}"/>
  <axis xyz ="1 0 0"/>
</joint>
</xacro:macro>



<xacro:macro name="mounting_plate" params="prefix z_coord parent">
<link name="${prefix}_mounting_plate">
  <visual>
    <geometry>
      <box size ="${mpx} ${mpy} ${mpz}"/>
    </geometry>
    <origin xyz ="0 0 ${mpz/2}"/>
  </visual>
</link>

<joint name="${parent}_to_${prefix}_mounting_plate" type="continuous">
  <parent link="${parent}"/>
  <child link="${prefix}_mounting_plate"/>
  <origin xyz="0 0 ${z_coord}"/>
  <axis xyz ="1 0 0"/>
</joint>
</xacro:macro>



<xacro:motor prefix="second" z_coord="${turntable_height/2}" parent="turntable"/>
<xacro:mounting_plate prefix="first" z_coord="${motorz}" parent="second_motor"/>


<link name="girder">
  <visual>
    <geometry>
      <box size ="${mpx} ${mpy} ${girder_len}"/>
    </geometry>
    <origin xyz ="0 0 ${girder_len/2}"/>
      <material name="cyan"/>
  </visual>
</link>

<joint name="first_mounting_plate_to_girder" type="fixed">
  <parent link="first_mounting_plate"/>
  <child link="girder"/>
  <origin xyz="0 0 ${mpz}"/>
  <axis xyz ="1 0 0"/>
</joint>

<xacro:motor prefix="third" z_coord="${girder_len}" parent="girder"/>
<xacro:mounting_plate prefix="second" z_coord="${motorz}" parent="third_motor"/>
<xacro:motor prefix="fourth" z_coord="${mpz}" parent="second_mounting_plate"/>
<xacro:mounting_plate prefix="third" z_coord="${motorz}" parent="fourth_motor"/>

</robot>
